version: "3.7"

services:
    site:
        build:
            context: ./site
            shm_size: "128MB"
        depends_on:
            - db
        hostname: site
        volumes:
            - ./site:/root/site:ro
            - ./tmp:/root/tmp:delegated
        ports:
            - 8080:80
            - 9222:9222
        networks:
            site-net:

    db:
        build: ./db
        hostname: db
        ports:
            - 8432:5432  
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            site-net:
                aliases:
                    - db # host connected to from django

volumes:
    db-vol:

networks:
    site-net:
