name: triggered continuous tests

on: [push]

jobs:
  check-style:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install flake8 pycodestyle
      - name: Style check with flake8
        working-directory: ./site
        run: flake8 .
      - name: Style check with pycodestyle
        if: always()
        working-directory: ./site
        run: pycodestyle .
  check-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Run docker-compose build site
        run: docker-compose build site
      - name: Run API tests
        run: docker-compose run -e CI_RUN=1 -T site runtest api
      - name: Run UI tests
        run: docker-compose run -e CI_RUN=1 -T site runtest ui
